apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    ipPools:
      - blockSize: 26
        cidr: 178.16.0.0/12
        encapsulation: None
        natOutgoing: Enabled
        nodeSelector: all()