apiVersion: tekton.dev/v1beta1
kind: Task
metadata: 
  name: t02-params
spec:
  params:
    - name: who
      type: string
  steps:
    - name: t02-params
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command: 
        - /bin/bash
        - -c
        - echo "Hello Tekton Params $(params.who)"
