apiVersion: tekton.dev/v1beta1
kind: Task
metadata: 
  name: t10-task-slow-10
spec:
  params:
    - name: taskname
      type: string
      default: slow-10
  steps:
    - name: t10-task-slow-can-fail-10
      image: registry.access.redhat.com/ubi8/ubi
      script: |
        #!/usr/bin/env bash
        echo "Performing Slow task > $(params.taskname)"
        dnf install iputils -y
        ping google.com -c 7
        echo "Sleeping for 10 seconds"
        sleep 10
        echo "Slow task $(params.taskname) commpleted!"
