# Git Clone and List Task Commands
# ? Value for param `gitrepository` of type `string`? 
# (Default is `https://github.com/MetaArivu/microservice-template.git`) 
# Please give specifications for the workspace: source
# ? Name for the workspace : source
# ? Value of the Sub Path :
# ? Type of the Workspace : emptyDir
# ? Type of EmptyDir :
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: t21-task-git-clone
spec:
  params: 
    - name: gitrepository
      type: string 
      description: Git repository to be cloned 
      default: https://github.com/MetaArivu/microservice-template.git
  workspaces:
    - name: source
  steps:
    - name: git-clone
      image: alpine/git
      workingDir: $(workspaces.source.path)
      command:
        - /bin/sh
      args: 
        - '-c'
        - git clone -v $(params.gitrepository) ./source
    - name: git-repo-list
      image: alpine
      workingDir: $(workspaces.source.path)
      command:
        - /bin/sh
      args:
        - "-c"
        - ls -la ./source
