# Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-shared-drive
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: "/tmp/data"