#!/bin/bash

echo "Chapter 1: Create Kubernetes Dashboard"
echo "1.1 Create Dashboard"
kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.1.0/aio/deploy/recommended.yaml

echo "1.2 Verify Dashboard"
kubectl get pod -n kubernetes-dashboard

echo "1.3 Create Cluster Role Binding"
kubectl create clusterrolebinding default-admin --clusterrole cluster-admin --serviceaccount=default:default

token=$(kubectl get secrets -o jsonpath="{.items[?(@.metadata.annotations['kubernetes\.io/service-account\.name']=='default')].data.token}"|base64 --decode)
echo
echo "1.4 Token $token"
echo

echo "http://localhost:8001/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:/proxy/#/login"

echo "1.5 Start the proxy"
kubectl proxy


