#!/bin/bash

echo "Chapter 1: Create Kubernetes Cluster"
echo "1.1 Create Multi Node Cluster with 1 Master, and 3 Worker Node"
echo "KinD Version >> "`kind version`
kind create cluster --config 1-clusters/delta-4.yaml

echo "1.2 Install NGINX Ingress Controller"
kubectl apply --filename https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml

echo "1.3 To Install the Apps run the following command"
echo "$ ch3-sigma-install-apps"
