#!/bin/bash

echo "Chapter 3: Deployment / Service Ingres / Horizontal Pod Auto Scaler (3-apps-deploy-service-ingress)"
echo "3.4 Delete the Apps"

kubectl delete  --filename 3-apps-deploy-service-ingress/ws-deploy.yaml
kubectl delete  --filename 3-apps-deploy-service-ingress/ws-service.yaml
kubectl delete  --filename 3-apps-deploy-service-ingress/tc8-deploy.yaml
kubectl delete  --filename 3-apps-deploy-service-ingress/tc8-service.yaml
kubectl delete  --filename 3-apps-deploy-service-ingress/tc9-deploy-v1.yaml
kubectl delete  --filename 3-apps-deploy-service-ingress/tc9-service.yaml
kubectl delete  --filename 3-apps-deploy-service-ingress/tc10-deploy.yaml
kubectl delete  --filename 3-apps-deploy-service-ingress/tc10-service.yaml
kubectl delete  --filename 3-apps-deploy-service-ingress/sigma-ingress.yaml
kubectl delete  --filename 3-apps-deploy-service-ingress/sigma-namespace.yaml

