#!/bin/bash

echo "Chapter 3: Deployment / Service Ingres / Horizontal Pod Auto Scaler (3-apps-deploy-service-ingress)"
echo "3.4 Delete the Apps"
kubectl delete  --filename 3-apps-deploy-service-ingress/
