#!/bin/bash

echo "Create Single Node Cluster"
kind create cluster --config clusters/alpha-1.yaml

echo "Install NGINX Ingress Controller"
kubectl apply --filename https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml

echo "To Install the Apps run the following command"
echo "$ install-apps"
