#!/bin/bash

echo "Create Multi Node Cluster with LB, 2 Masters, and 1 Worker Node"
kind create cluster --config 1-clusters/gamma-3.yaml

echo "Install NGINX Ingress Controller"
kubectl apply --filename https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml

echo "To Install the Apps run the following command"
echo "$ install-apps"
