#!/bin/bash

echo "1.1Installing Tekton in Kubernetes Cluster"
kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml

sleep 10
echo ""
echo "1.2 Check the Tekton Pod Status"
kubectl get pods --namespace tekton-pipelines

echo "1.3 Setup Tekton Dashboard"
kubectl apply --filename https://github.com/tektoncd/dashboard/releases/latest/download/tekton-dashboard-release.yaml

echo "1.4 Setup Tekton Triggers"
kubectl apply --filename https://storage.googleapis.com/tekton-releases/triggers/latest/release.yaml
kubectl apply --filename https://storage.googleapis.com/tekton-releases/triggers/latest/interceptors.yaml

sleep 20
echo "1.5 Port forward to 9097"
echo "kubectl --namespace tekton-pipelines port-forward svc/tekton-dashboard 9097:9097 &"
kubectl --namespace tekton-pipelines port-forward svc/tekton-dashboard 9097:9097 &
# Other Way
#kubectl proxy --port=9097 &
#Browser
# echo http://localhost:9097/api/v1/namespaces/tekton-pipelines/services/tekton-dashboard:http/proxy/#/pipelines


echo "1.6 Switch the Namespace to tekton-pipelines"
kubectl config set-context $(kubectl config current-context) --namespace=tekton-pipelines
echo ""
echo "Tekton Dashboard http://localhost:9097"

