#########################################
#
# (C) MetaMagic Global Inc, NJ, USA, 2021
#
# Arivu Services & Containers
#
# Version 0.2
#
#########################################
# 
FROM hashicorp/http-echo:0.2.3

EXPOSE 5678/tcp

ENTRYPOINT ["/http-echo"]
