kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: beta-2
networking:
  # Based on RFC 1918
  podSubnet: "178.16.0.0/12"
  serviceSubnet: "196.168.0.0/16"
nodes:
# 2 Node Cluster (1 Master and Worker Node)
# Master Node
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
# Worker Node
- role: worker
