#!/bin/bash

echo "Chapter 1: Create Kubernetes Cluster with Istio"
echo "1.1 Create Multi Node Cluster with 1 Master, and 2 Worker Nodes"
echo "KinD Version >> "`kind version`
kind create cluster --config setup/gamma-cluster-3-nodes.yaml

#echo "1.2 Install NGINX Ingress Controller"
#echo "kubectl apply --filename https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml"
#kubectl apply --filename https://raw.githubusercontent.com/kubernetes/ingress-nginx/master/deploy/static/provider/kind/deploy.yaml

# Calico
echo "1.2 Install Calico Network Driver"
kubectl create -f https://docs.projectcalico.org/manifests/tigera-operator.yaml
kubectl apply -f setup/calico.yaml

sleep 10
kubectl get pods -n calico-system

# Metrics Server
echo "1.3 Install Metrics Server"
sleep 120

kubectl config set-context --current --namespace kube-system

helm repo add stable https://kubernetes-charts.storage.googleapis.com
helm repo update
helm upgrade metrics-server --install --set "args={--kubelet-insecure-tls, --kubelet-preferred-address-types=InternalIP}" stable/metrics-server --namespace kube-system

echo "1.4 Install Istio"
kubectl apply -f setup/install-istio.yaml
echo "1.5 To Install the Apps run the following command"
echo "$ ch3-sigma-install-apps"
