#!/bin/bash
echo "curl -X 'GET'   'http://localhost/api/v1/$1/service/live'   -H 'accept: application/json'"
curl -X 'GET'   "http://localhost/api/v1/$1/service/live"   -H 'accept: application/json'
echo 
